package com.lqy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROVINCE.
 */
public class Province {

    private Long id;
    /** Not-null value. */
    private String province_name;
    private String province_code;

    public Province() {
    }

    public Province(Long id) {
        this.id = id;
    }

    public Province(Long id, String province_name, String province_code) {
        this.id = id;
        this.province_name = province_name;
        this.province_code = province_code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getProvince_name() {
        return province_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProvince_name(String province_name) {
        this.province_name = province_name;
    }

    public String getProvince_code() {
        return province_code;
    }

    public void setProvince_code(String province_code) {
        this.province_code = province_code;
    }

}
